
function seqs=configSeqs(path)

seqVTD={struct('name','soccer','path',[path '\' 'OTB50\Soccer\img\'],'startFrame',1,'endFrame',392,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','matrix','path',[path '\' 'OTB50\Matrix\img\'],'startFrame',1,'endFrame',100,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','ironman','path',[path '\' 'OTB50\Ironman\img\'],'startFrame',1,'endFrame',166,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','deer','path',[path '\' 'OTB50\Deer\img\'],'startFrame',1,'endFrame',71,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','skating1','path',[path '\' 'OTB50\Skating1\img\'],'startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','shaking','path',[path '\' 'OTB50\Shaking\img\'],'startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','singer1','path',[path '\' 'OTB50\Singer1\img\'],'startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','singer2','path',[path '\' 'OTB50\Singer2\img\'],'startFrame',1,'endFrame',366,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};

seqIVT={struct('name','carDark','path',[path '\' 'OTB50\CarDark\img\'],'startFrame',1,'endFrame',393,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','car4','path',[path '\' 'OTB50\Car4\img\'],'startFrame',1,'endFrame',659,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david','path',[path '\' 'OTB50\David\img\'],'startFrame',300,'endFrame',770,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david2','path',[path '\' 'OTB50\David2\img\'],'startFrame',1,'endFrame',537,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...    
    struct('name','sylvester','path',[path '\' 'OTB50\Sylvester\img\'],'startFrame',1,'endFrame',1345,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','trellis','path',[path '\' 'OTB50\Trellis\img\'],'startFrame',1,'endFrame',569,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','fish','path',[path '\' 'OTB50\Fish\img\'],'startFrame',1,'endFrame',476,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','mhyang','path',[path '\' 'OTB50\Mhyang\img\'],'startFrame',1,'endFrame',1490,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};

seqOther={struct('name','coke','path',[path '\' 'OTB50\Coke\img\'],'startFrame',1,'endFrame',291,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','bolt','path',[path '\' 'OTB50\Bolt\img\'],'startFrame',1,'endFrame',350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','boy','path',[path '\' 'OTB50\Boy\img\'],'startFrame',1,'endFrame',602,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','dudek','path',[path '\' 'OTB50\Dudek\img\'],'startFrame',1,'endFrame',1145,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','crossing','path',[path '\' 'OTB50\Crossing\img\'],'startFrame',1,'endFrame',120,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','couple','path',[path '\' 'OTB50\Couple\img\'],'startFrame',1,'endFrame',140,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','football1','path',[path '\' 'OTB50\Football1\img\'],'startFrame',1,'endFrame',74,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jogging-1','path',[path '\' 'OTB50\Jogging\img\'],'startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jogging-2','path',[path '\' 'OTB50\Jogging\img\'],'startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','doll','path',[path '\' 'OTB50\Doll\img\'],'startFrame',1,'endFrame',3872,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','girl','path',[path '\' 'OTB50\Girl\img\'],'startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','walking2','path',[path '\' 'OTB50\Walking2\img\'],'startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','walking','path',[path '\' 'OTB50\Walking\img\'],'startFrame',1,'endFrame',412,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','fleetface','path',[path '\' 'OTB50\Fleetface\img\'],'startFrame',1,'endFrame',707,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','freeman1','path',[path '\' 'OTB50\Freeman1\img\'],'startFrame',1,'endFrame',326,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','freeman3','path',[path '\' 'OTB50\Freeman3\img\'],'startFrame',1,'endFrame',460,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','freeman4','path',[path '\' 'OTB50\Freeman4\img\'],'startFrame',1,'endFrame',283,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david3','path',[path '\' 'OTB50\David3\img\'],'startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jumping','path',[path '\' 'OTB50\Jumping\img\'],'startFrame',1,'endFrame',313,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','carScale','path',[path '\' 'OTB50\CarScale\img\'],'startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','skiing','path',[path '\' 'OTB50\Skiing\img\'],'startFrame',1,'endFrame',81,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','dog1','path',[path '\' 'OTB50\Dog1\img\'],'startFrame',1,'endFrame',1350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','suv','path',[path '\' 'OTB50\Suv\img\'],'startFrame',1,'endFrame',945,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','motorRolling','path',[path '\' 'OTB50\MotorRolling\img\'],'startFrame',1,'endFrame',164,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','mountainBike','path',[path '\' 'OTB50\MountainBike\img\'],'startFrame',1,'endFrame',228,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),... 
    struct('name','lemming','path',[path '\' 'OTB50\Lemming\img\'],'startFrame',1,'endFrame',1336,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','liquor','path',[path '\' 'OTB50\Liquor\img\'],'startFrame',1,'endFrame',1741,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','woman','path',[path '\' 'OTB50\Woman\img\'],'startFrame',1,'endFrame',597,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','faceocc1','path',[path '\' 'OTB50\Faceocc1\img\'],'startFrame',1,'endFrame',892,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','faceocc2','path',[path '\' 'OTB50\Faceocc2\img\'],'startFrame',1,'endFrame',812,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','basketball','path',[path '\' 'OTB50\Basketball\img\'],'startFrame',1,'endFrame',725,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','football','path',[path '\' 'OTB50\Football\img\'],'startFrame',1,'endFrame',362,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','subway','path',[path '\' 'OTB50\Subway\img\'],'startFrame',1,'endFrame',175,'nz',4,'ext','jpg','init_rect', [0 0 0 0]),...    
    struct('name','tiger1','path',[path '\' 'OTB50\Tiger1\img\'],'startFrame',1,'endFrame',354,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','tiger2','path',[path '\' 'OTB50\Tiger2\img\'],'startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};
    OTB2013 = [seqIVT,seqVTD,seqOther];
    OTB2015 = {
        struct('name','bird1','path',[path '\' 'OTB100\Bird1\img\'],'startFrame',1,'endFrame',408,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','bird2','path',[path '\' 'OTB100\Bird2\img\'],'startFrame',1,'endFrame',99,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','board','path',[path '\' 'OTB100\Board\img\'],'startFrame',1,'endFrame',698,'nz',5,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','box','path',[path '\' 'OTB100\Box\img\'],'startFrame',1,'endFrame',1161,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','biker','path',[path '\' 'OTB100\Biker\img\'],'startFrame',1,'endFrame',142,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...  
        struct('name','blurBody','path',[path '\' 'OTB100\BlurBody\img\'],'startFrame',1,'endFrame',334,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','blurCar1','path',[path '\' 'OTB100\BlurCar1\img\'],'startFrame',247,'endFrame',988,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','blurCar2','path',[path '\' 'OTB100\BlurCar2\img\'],'startFrame',1,'endFrame',585,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','blurCar3','path',[path '\' 'OTB100\BlurCar3\img\'],'startFrame',3,'endFrame',359,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','blurCar4','path',[path '\' 'OTB100\BlurCar4\img\'],'startFrame',18,'endFrame',397,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','blurFace','path',[path '\' 'OTB100\BlurFace\img\'],'startFrame',1,'endFrame',493,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','blurOwl','path',[path '\' 'OTB100\BlurOwl\img\'],'startFrame',1,'endFrame',631,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...%%
         struct('name','bolt2','path',[path '\' 'OTB100\Bolt2\img\'],'startFrame',1,'endFrame',293,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...%%
         struct('name','car1','path',[path '\' 'OTB100\Car1\img\'],'startFrame',1,'endFrame',1020,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...%
         struct('name','car2','path',[path '\' 'OTB100\Car2\img\'],'startFrame',1,'endFrame',913,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
          struct('name','car24','path',[path '\' 'OTB100\Car24\img\'],'startFrame',1,'endFrame',3059,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
          struct('name','clifBar','path',[path '\' 'OTB100\ClifBar\img\'],'startFrame',1,'endFrame',329,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...%%%%%473
           struct('name','coupon','path',[path '\' 'OTB100\Coupon\img\'],'startFrame',1,'endFrame',327,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
           struct('name','crowds','path',[path '\' 'OTB100\Crowds\img\'],'startFrame',1,'endFrame',347,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
           struct('name','dancer','path',[path '\' 'OTB100\Dancer\img\'],'startFrame',1,'endFrame',225,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','dancer2','path',[path '\' 'OTB100\Dancer2\img\'],'startFrame',1,'endFrame',150,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','diving','path',[path '\' 'OTB100\Diving\img\'],'startFrame',1,'endFrame',215,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','dog','path',[path '\' 'OTB100\Dog\img\'],'startFrame',1,'endFrame',127,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','dragonBaby','path',[path '\' 'OTB100\DragonBaby\img\'],'startFrame',1,'endFrame',113,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','girl2','path',[path '\' 'OTB100\Girl2\img\'],'startFrame',1,'endFrame',1500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','gym','path',[path '\' 'OTB100\Gym\img\'],'startFrame',1,'endFrame',767,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','human2','path',[path '\' 'OTB100\Human2\img\'],'startFrame',1,'endFrame',1128,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','human3','path',[path '\' 'OTB100\Human3\img\'],'startFrame',1,'endFrame',1698,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','human4','path',[path '\' 'OTB100\Human4\img\'],'startFrame',1,'endFrame',667,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','human5','path',[path '\' 'OTB100\Human5\img\'],'startFrame',1,'endFrame',713,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','human6','path',[path '\' 'OTB100\Human6\img\'],'startFrame',1,'endFrame',792,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
            struct('name','human7','path',[path '\' 'OTB100\Human7\img\'],'startFrame',1,'endFrame',250,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','human8','path',[path '\' 'OTB100\Human8\img\'],'startFrame',1,'endFrame',128,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','human9','path',[path '\' 'OTB100\Human9\img\'],'startFrame',1,'endFrame',305,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','jump','path',[path '\' 'OTB100\Jump\img\'],'startFrame',1,'endFrame',122,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','kitesurf','path',[path '\' 'OTB100\KiteSurf\img\'],'startFrame',1,'endFrame',84,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','man','path',[path '\' 'OTB100\Man\img\'],'startFrame',1,'endFrame',134,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','panda','path',[path '\' 'OTB100\Panda\img\'],'startFrame',1,'endFrame',1000,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','redTeam','path',[path '\' 'OTB100\RedTeam\img\'],'startFrame',1,'endFrame',1918,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','rubik','path',[path '\' 'OTB100\Rubik\img\'],'startFrame',1,'endFrame',1997,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','skater','path',[path '\' 'OTB100\Skater\img\'],'startFrame',1,'endFrame',160,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','skater2','path',[path '\' 'OTB100\Skater2\img\'],'startFrame',1,'endFrame',435,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','skating2-1','path',[path '\' 'OTB100\Skating2\img\'],'startFrame',1,'endFrame',473,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','skating2-2','path',[path '\' 'OTB100\Skating2\img\'],'startFrame',1,'endFrame',473,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','surfer','path',[path '\' 'OTB100\Surfer\img\'],'startFrame',1,'endFrame',376,'nz',4,'ext','jpg','init_rect', [0,0,0,0])...
         struct('name','toy','path',[path '\' 'OTB100\Toy\img\'],'startFrame',1,'endFrame',271,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','trans','path',[path '\' 'OTB100\Trans\img\'],'startFrame',1,'endFrame',124,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','twinnings','path',[path '\' 'OTB100\Twinnings\img\'],'startFrame',1,'endFrame',472,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
         struct('name','vase','path',[path '\' 'OTB100\Vase\img\'],'startFrame',1,'endFrame',271,'nz',4,'ext','jpg','init_rect', [0,0,0,0])
        };
    TestSets ={
        struct('name','tiger1','path',[path '\' 'OTB50\Tiger1\img\'],'startFrame',1,'endFrame',354,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
        struct('name','tiger2','path',[path '\' 'OTB50\Tiger2\img\'],'startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0])
        };
seqs=[OTB2013,OTB2015];%,,TestSets
